name: Release libmcphase on PyPI

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  create_release:
    name: Creates a PyPI release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install twine requests numpy
          python release.py --notest --pypi
          twine upload twine_wheelhouse/*.whl
